name: main

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Compile
        run: npx tsc

      - name: Unit tests
        run: npm test

      - name: Integration tests
        run: |
          npm run test:server &
          SERVER_PID=$!
          sleep 2
          node tests/integration/run.mjs
          kill $SERVER_PID